name: dartffiedlibdecaf
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  sha3: ^0.2.0

dev_dependencies:
  pedantic: ^1.9.0
  ffigen: ^3.0.0
  test: ^1.17.10
  lints: ^1.0.1

ffigen:
  name: "libdecaf"
  output: "libdecaf_generated_bindings.dart"
  headers:
    entry-points:
      - "libdecaf/src/GENERATED/include/**.h"
      - "libdecaf/src/GENERATED/include/decaf/**.h"
  compiler-opts: "-I libdecaf/src/GENERATED/include"
