name: sign_dart
version: 1.0.0
description: Pure Dart library for elliptic curve research and practical application. EdDSA, Ed448, Ed521.
repository: https://github.com/pbad-pades/SignDart
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  sha3: ^0.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.10
  lints: ^1.0.1