name: SignDartPublish

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["SignDartAnalyze"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: true
